-- ─────────────────────────────────────────────────────────────────────────────
-- ATENÇÃO: este arquivo é um artefato do MVP inicial e está DESATUALIZADO.
--
-- A fonte de verdade do schema é:
--   prisma/schema.prisma
--
-- Para aplicar o schema no banco:
--   npx prisma db push          (desenvolvimento)
--   npx prisma migrate deploy   (produção)
--
-- Não use este arquivo para provisionar ou recriar o banco de dados.
-- ─────────────────────────────────────────────────────────────────────────────
