ALTER TYPE "TipoMensagemWhatsApp" ADD VALUE IF NOT EXISTS 'PEDIDO_AGUARDANDO';
ALTER TYPE "TipoMensagemWhatsApp" ADD VALUE IF NOT EXISTS 'PEDIDO_EM_PREPARO';
ALTER TYPE "TipoMensagemWhatsApp" ADD VALUE IF NOT EXISTS 'PEDIDO_ENTREGUE';
